run:
  timeout: 3m
  tests: true
linters:
  enable:
    - govet
    - gosec
    - gosimple
    - staticcheck
    - ineffassign
    - misspell
    - unused
    - prealloc
  disable:
    - errcheck
issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
linters-settings:
  misspell:
    locale: US
